# Generated by Django 5.2.3 on 2025-06-15 14:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('nombre_places', models.IntegerField()),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('cle_utilisateur', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('admin', 'Administrateur')], default='client', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PanierOffre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetterie.offre')),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetterie.panier')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetterie.utilisateur'),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_commande', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('cle_finale', models.CharField(max_length=255)),
                ('qrcode', models.TextField(blank=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billetterie.utilisateur')),
            ],
        ),
    ]
